[_]: Feat/Add lastPasswordChangeAt to users
internxt/drive-server-wip pull request #148
Opened 2023-02-27 17:39 UTC by larry-internxt

- Added lastPasswordChangeAt column to users

2023-02-28 12:23 UTC, sg-gs commented on migrations/20230227160000-add-lastPasswordChangedAt-to-users.js
> +      allowNull: true,
same comment as on the drive-server PR regarding null values

2024-01-05 17:04 UTC, apsantiso commented
@sg-gs I checked this PR is also related with PB-267 which is still in progress, can we accept this PR as it is and add the middleware later? 

We could have a simple function to check the token that we can use both in the middleware and in the endpoint for https://github.com/internxt/drive-server-wip/pull/250.  

Public endpoints (as auto unblock account) don´t pass through the middleware we don´t rely on the implementation that is still in progress.

what do you think?

2024-01-09 14:55 UTC, sg-gs requested changes

2024-01-09 14:55 UTC, sg-gs commented on migrations/20240109071854-add-lastPasswordChangedAt-to-users.js
> +    if (!tableDefinition[newColumn]) {
The migrations should be idempotent, not dependent on the environment. Do not worry about production, we will run a clean migration.

2024-01-09 14:55 UTC, sg-gs commented on migrations/20240109071854-add-lastPasswordChangedAt-to-users.js
> +    if (!tableDefinition[newColumn]) {
The migrations should be idempotent, not dependent on the environment. Do not worry about production, we will run a clean migration.

2024-01-09 14:55 UTC, sg-gs commented on src/modules/auth/jwt.strategy.spec.ts
> +    const greaterDate = new Date();
To ensure that this case is not failing, please, do use the token iat as the base date for a new Date, and the add the minutes. If the tests start to run slowly, this test could not pass. The tests should be consistent always. For instance: 

```
const user = newUser();
const tokenIat = getTokenDefaultIat();
const olderDate = new Date(tokenIat);
olderDate.setMinutes(olderDate.getMinutes() + 1);
// and so on ..
```

2024-01-09 14:55 UTC, sg-gs commented on src/modules/auth/jwt.strategy.spec.ts
> +    const olderDate = new Date();
Same here. Switching the orders of both things could make the tests pass. The control of the things that determine if the tests passes or not should be clear here. Ideally, we should not have to check the internal code to be sure that the tests works as expected

2024-01-09 15:45 UTC, sg-gs approved these changes

2024-01-09 16:17 UTC, merged