[PB-535]: feat/return list of folders shared with a user
internxt/drive-server-wip pull request #163
Opened 2023-06-09 00:27 UTC by cg27shokworks

WIP: Missing tests via swagger

2023-06-16 11:37 UTC, sg-gs requested changes
I recommend re-checking the Confluence documentation regarding this task first. We have a different domain for private sharing but this codebase is working on the public sharing domain

2023-06-16 11:37 UTC, sg-gs commented on src/modules/share/share.controller.ts
> +      const Folders = await this.shareUseCases.getSharedFoldersToAUser(
use camelCase please

2023-06-16 11:37 UTC, sg-gs commented on src/modules/share/share.repository.ts
> +      throw new BadRequestException('take and skip must be provided together');
Let's handle HTTP things on the controller layer please

2023-06-16 11:37 UTC, sg-gs commented on src/modules/share/share.repository.ts
> +        user_id: user.id,
use camelCase

2023-06-16 11:37 UTC, sg-gs commented on src/modules/share/share.repository.ts
> +    const findCriteria = {
I will type this if we are going to split it from the `findAll`

2023-06-16 11:37 UTC, sg-gs commented on src/modules/share/share.repository.ts
> +    if (!isNaN(limit) && !isNaN(offset)) {
The repository layer should persist data only, the responsibility of validating the data should be done by the controller. All the controllers must validate the data so any usecase/repository receives the data in the expected format. If we have types for variables but we still have to validate things on the entire codebase, then TypeScript is not worth it

2023-06-16 11:37 UTC, sg-gs commented on src/modules/share/share.repository.ts
> +    const folders = shares.map((share) => share.folder.toJSON());
return directly

2023-06-16 11:37 UTC, sg-gs commented on src/modules/share/share.repository.ts
> +    const shares = await this.shareModel.findAll(findCriteria);
According to the confluence documentation, we should return **the private folders** shared by a user with another user, shares table is for public sharing

2023-06-19 23:25 UTC, cg27shokworks commented
I will close this PR to open another one based on https://github.com/internxt/drive-server-wip/pull/168 changes.

2023-06-19 23:25 UTC, closed without merging