[PB-535]: feat/return private folder shared with a user
internxt/drive-server-wip pull request #169
Opened 2023-06-20 00:52 UTC by cg27shokworks

2023-06-23 08:53 UTC, sg-gs requested changes

2023-06-23 08:53 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.controller.ts
> +  async getReceivedFolders(
I found this name a bit confusing

2023-06-23 08:53 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.repository.ts
> +  async findSharedWithMePrivateFolders(
Too much business-related

2023-06-29 15:17 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.repository.ts
> +          foreignKey: 'folderUuid',
Why `folderUuid`?

2023-06-30 04:44 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing.repository.ts
> +          foreignKey: 'folderUuid',
Fixed, possibly a copilot completion error.

2023-07-03 13:19 UTC, sg-gs approved these changes

2023-07-03 13:19 UTC, merged