[PB-620] stop sharing
internxt/drive-server-wip pull request #192
Opened 2023-08-03 19:54 UTC by miguelsw

2023-08-07 17:30 UTC, cg27shokworks requested changes

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing.usecase.ts
> +    super('User is not in shared folder');
same here

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
> +  async removeByUser(folderUuid: string, userUuid: string): Promise<any> {
You must match the typing here with what is specified in the interface.

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
> +  async findByFolder(folderUuid: string): Promise<PrivateSharingFolderRole[]> {
You must match the typing here with what is specified in the interface.

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
> +  async removeByFolder(folderUuid: string): Promise<any> {
You must match the typing here with what is specified in the interface.

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
> +  async findByFolderAndUser(
You must match the typing here with what is specified in the interface.

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing.controller.ts
> +        `[PRIVATESHARING/STOP] ERROR: ${
You must catch the specific errors defined in the use case and handle them. This error for example:

https://github.com/internxt/drive-server-wip/blob/59fe6c7bbd4c8732691028b6491a26f714655c21/src/modules/private-share-folder/private-sharing.usecase.ts#L101

how to do it :
https://github.com/internxt/drive-server-wip/blob/59fe6c7bbd4c8732691028b6491a26f714655c21/src/modules/folder/folder.controller.ts#L304

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing.controller.ts
> +        `[PRIVATESHARING/REMOVE] ERROR: ${
same here

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing.repository.ts
> +  async removeByFolderUuid(folderUuid: string): Promise<any> {
check type

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing.repository.ts
> +  async removeBySharedWith(folderUuid: string, userUuid: string): Promise<any> {
same here

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing.usecase.ts
> +    super('This folder is not shared');
You must add 

Object.setPrototypeOf(this, FolderNotSharedError .prototype)

this ensures that the created error instance has the correct prototype, and the proper functioning of instanceof in the controller's catch

2023-08-07 17:30 UTC, cg27shokworks commented on src/modules/private-share-folder/private-sharing.usecase.ts
> +    folderUuid: string,
check types

2023-08-09 11:41 UTC, sg-gs requested changes

2023-08-09 11:41 UTC, sg-gs commented on src/modules/folder/folder.usecase.ts
> +  constructor() {
Please use [this](https://github.com/internxt/drive-server-wip/blob/cc313904b564f55293fb6d0ce1b2482acf548ead/src/modules/user/user.usecase.ts#L47) so the `instanceof` check works properly

2023-08-09 11:41 UTC, sg-gs commented on src/modules/folder/folder.usecase.ts
> +  async getFolderByUuid(folderUuid: FolderAttributes['uuid']): Promise<Folder> {
This method already [exists](https://github.com/internxt/drive-server-wip/blob/master/src/modules/folder/folder.usecase.ts#L41). 

Also, I do not see this function being used on any of the introduced changes. If it is going to be used, use the already existing one.

If this is needed for accessing a folder by an invited user, you should: 
- Create a use case on private sharing folder use-cases (`getFolderByInvitedUser` p.e) where you check that the user has the proper permissions to access it, and then you pass to the already existent function here, the owner user object.

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
> +    return await this.removeByField({ folderId: folderUuid, userId: userUuid });
return directly and remove `async-await` from here

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
> +    return await this.removeByField({ folderId: folderUuid });
Same here regarding to `async-await`

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
> +    const sharedFolderRolesByFolder =
`return` directly

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing-folder-roles.repository.ts
> +    const sharedFolderRolesByFolderAndUser =
`return` directly

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.controller.ts
> +  @Delete('stop/folder-id/:folderId')
You are deleting a resource here, why not `DELETE /:id` ? As you are deleting a private sharing, then before deleting you match that the user id requesting this OR the `owner_id` OR the `shared_with`

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.controller.ts
> +  @Delete('remove/folder-id/:folderId/user-id/:userId')
The HTTP Method is DELETE, `remove` word usage then, is redundant. Also, matching with the private-sharing id as the above endpoint is enough, I think

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.repository.ts
> +    const amountRemoves = await this.privateSharingFolderModel.destroy({
return directly so you can remove `async-await`

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.repository.ts
> +    const privatesRemovedByFolderUuid = await this.removeByField({
return directly so you can remove `async-await`

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.repository.ts
> +    const sharedWithRemoved = await this.removeByField({
return directly so you can remove `async-await`

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.repository.ts
> +    const sharedFolders = await this.privateSharingFolderModel.findAll({
return directly so you can remove `async-await`

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.repository.ts
> +    const sharedFolders = await this.privateSharingFolderModel.findAll({
return directly so you can remove `async-await`

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.controller.ts
> +      return await this.privateSharingUseCase.stopSharing(folderUuid);
`await` here is redundant

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.usecase.ts
> +  async stopSharing(folderUuid: Folder['uuid']): Promise<any> {
Well, this is called from the controller so, as far as I have a JWT authorized and I know the folder `uuid` which I want to remove **I would be able to do so, even if it is not mine, even if I am not even related to this.** 

_Security is not an option, is a must._

2023-08-09 11:41 UTC, sg-gs commented on src/modules/private-share-folder/private-sharing.usecase.ts
Check on this file that only authorized actors are able to perform the actions, please.

2023-08-16 10:20 UTC, sg-gs approved these changes

2023-08-16 10:23 UTC, merged