Feat/invite users on sharing
internxt/drive-server-wip pull request #222
Opened 2023-10-31 17:48 UTC by apsantiso

2023-11-14 12:38 UTC, sg-gs requested changes

2023-11-14 12:38 UTC, sg-gs commented on src/modules/sharing/models/index.ts
> +  sharedWithPreCreatedUser: UserModel;
I think should be: 
`sharedWithPreCreatedUser: PreCreatedUserModel;`
Isn't?

2023-11-14 12:38 UTC, sg-gs commented on src/modules/sharing/sharing.controller.ts
> +  async validateInvite(@Param('id') id: SharingInvite['id']) {
async is not needed here, although you do a try catch. I would advise adding a try-catch with a log.

2023-11-14 12:38 UTC, sg-gs commented on src/modules/user/pre-created-users.repository.ts
> +    const user = await this.modelUser.findByPk(id);
return directly instead of using async - await. Also, we are not converting this to domain

2023-11-14 12:38 UTC, sg-gs commented on src/modules/user/pre-created-users.repository.ts
> +    return user;
Not converted to the domain

2023-11-14 12:40 UTC, sg-gs commented
Nice job here @apsantiso. Give to this a thought: 
- What if a bad actor tries to pre-register a given list of emails to prevent those real users to sign up? 

I suggest to handle that case on the current signup, adding a path where if the user is pre-created and tries to sign up, we remove the pre-created one and migrate the invites to the real new user. Thus, we do not allow anyone to be able to block users from joining Internxt.

2023-11-14 12:47 UTC, apsantiso commented
> Nice job here @apsantiso. Give to this a thought:
> 
> * What if a bad actor tries to pre-register a given list of emails to prevent those real users to sign up?
> 
> I suggest to handle that case on the current signup, adding a path where if the user is pre-created and tries to sign up, we remove the pre-created one and migrate the invites to the real new user. Thus, we do not allow anyone to be able to block users from joining Internxt.

@sg-gs Yes, I thought about handling that case together with the ticket related to register pre created users as we dont want to block any user from signin up. However, that tickets seems to be taking time so I don't have problem with covering that case in this PR quickly.

2023-11-15 03:14 UTC, apsantiso commented on src/modules/user/user.usecase.ts
> +        encryptedMessage: Buffer.from(invite.encryptionKey, 'base64').toString(
frontend side we are using aob and btoa but they are marked as deprecated by Nodejs, so used Buffer to accomplish the same behavior.  Same as below with buffer.from(xxx, 'binary')

2023-11-15 15:41 UTC, sg-gs approved these changes

2023-11-15 16:32 UTC, merged