Feat/workspaces main
internxt/drive-server-wip pull request #287
Opened 2024-03-07 18:59 UTC by apsantiso

2024-03-14 04:35 UTC, apsantiso commented on src/modules/gateway/gateway.controller.ts
> +  @Public()
This is just to skip the globalGuard(AuthGuard) that tries to verify an user based token.

2024-03-14 13:05 UTC, sg-gs requested changes

2024-04-19 15:04 UTC, apsantiso commented
/check-preview notify=true

2024-04-22 00:31 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-c6cf318d2b9c20cfc0ffb3cb5586737cf422acbd

2024-04-22 03:47 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-d405cbaf3037800830dc1d1730787f33f2c055bc

2024-04-22 13:38 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-1f909fa049bd0158330a2240e09c40f708cf5a91

2024-04-22 16:03 UTC, apsantiso commented
/check-preview notify=true

2024-04-24 16:21 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-c507a2d8fddc240dc8e68e0f39ece20d1514cbde

2024-04-29 04:24 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-c1a19b8dfbdb5c0d85c8db45f18de3bde1a4e865

2024-04-30 04:42 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-fb647a12bdd77ae6f76df285bb21ce9f8fc59d1f

2024-05-07 16:04 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-3edc3cbf3b3874856c0ddf9505ab809840332491

2024-05-09 10:35 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-5b46950c80119edc624fb90be810bbd266fa13bf

2024-05-09 10:43 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-6b12e881dc0b8488a879e9747728d177be6f0ae9

2024-05-09 13:54 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-76835a7d99ce16d241696c1fd8dc67b066aa02a7

2024-05-16 17:24 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-69edc19ab99b81a6a90438f04c7e7a0f52efcfca

2024-05-17 00:18 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-c672bc3707778b928b915932e099ad1a459b8ac7

2024-05-21 14:30 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-735f3e44825740960d2b05ceb2262f13107b08bf

2024-05-21 16:07 UTC, apsantiso commented
/check-preview notify=true

2024-05-22 13:07 UTC, apsantiso commented
/check-preview notify=true

2024-05-22 13:07 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-e2c2dd574ecf98c030ce63506b429146d8476b04

2024-05-22 13:26 UTC, apsantiso commented
/check-preview notify=true

2024-05-22 14:00 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-d56566e75c284dd862dbc9d02efcf42858d8518f

2024-05-24 07:21 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-3eeaab11ba3a0cda46a6216c3bf28dda2e78f7d2

2024-05-24 13:08 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-02fbdc80e8ef5bdc3428cef47ee875e681d967c1

2024-05-25 22:04 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-64c4ed5848e40313d46f9516de6e46f602904e5f

2024-05-26 00:01 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-258e44746e5eca876a730b3a0e6044401a62bd93

2024-05-29 00:42 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-912abbe3eb2130b47b2bfc53f34841a4854faa0c

2024-05-31 04:58 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-0d904ee54caf74a979a1e4456b9ed6bcaca07a2b

2024-06-03 17:07 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-846d9214e6df4f12d2a1616780eac7bcb3d4a955

2024-06-05 18:19 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-46b75d4f267bcfb8d31dd386df030f27108b43b3

2024-06-05 18:30 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-33ceda9fcf18603091972a25418ea4b4cbe7ca1b

2024-06-10 20:53 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-feaff6597ba24c071ffb82741e8c62ac5e0f5020

2024-06-11 13:42 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-41c1aa71e2536ddf019f3cf1409ff75bc0d51e6d

2024-06-13 00:03 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-dd6257ed86adb4c23ecba2603fbf48967544df8f

2024-06-13 00:04 UTC, apsantiso commented
/check-preview notify=true

2024-06-13 00:08 UTC, inxtci commented
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Progressing**

2024-06-13 04:09 UTC, inxtci commented
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Progressing**

2024-06-13 05:06 UTC, apsantiso commented
/check-preview notify=true

2024-06-13 15:37 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-9866b8671acdf06bbdde8024155f8de17dcbfc94

2024-06-14 06:04 UTC, apsantiso commented
/update-preview drive-server preview-442-YTNiOTMxOTgyYTZlY2FjM2M0Y2VjMT imageSuffix=-dev

2024-06-14 06:31 UTC, apsantiso commented
/check-preview notify=true

2024-06-14 06:33 UTC, apsantiso commented
/update-preview drive-server preview-442-YTNiOTMxOTgyYTZlY2FjM2M0Y2VjMT imageSuffix=-dev

2024-06-14 06:55 UTC, apsantiso commented
/update-preview drive-server preview-442-a3b931982a6ecac3c4cec142a80cb6f9d0aef64f imageSuffix=-dev

2024-06-14 14:42 UTC, apsantiso commented
/update-preview drive-server preview-442-af72fd9d5589d9a7c7451126f5450835c36ba6c2 imageSuffix=-dev

2024-06-14 14:57 UTC, apsantiso commented
/update-preview drive-server preview-442-af72fd9d5589d9a7c7451126f5450835c36ba6c2 imageSuffix=-dev

2024-06-18 03:39 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-c335395923a8e8dad2451eb5a09d8396429b2c6f

2024-06-18 03:59 UTC, apsantiso commented
/update-preview drive-server preview-442-af72fd9d5589d9a7c7451126f5450835c36ba6c2 imageSuffix=-dev

2024-06-18 09:13 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-c335395923a8e8dad2451eb5a09d8396429b2c6f

2024-06-18 12:48 UTC, apsantiso commented
/update-preview drive-server preview-442-af72fd9d5589d9a7c7451126f5450835c36ba6c2 imageSuffix=-dev

2024-06-18 14:45 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-e8c9bc432b103922a9c3be1a7d46dec1f0ed8d34

2024-06-18 14:46 UTC, apsantiso commented
/update-preview drive-server preview-442-af72fd9d5589d9a7c7451126f5450835c36ba6c2 imageSuffix=-dev

2024-06-18 16:41 UTC, apsantiso commented
/update-preview drive-server preview-442-af72fd9d5589d9a7c7451126f5450835c36ba6c2 imageSuffix=-dev

2024-06-19 02:48 UTC, apsantiso commented
/update-preview drive-server preview-443-f4e98fad68b03afa671ea125f6d969113305547e imageSuffix=-dev

2024-06-19 12:41 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-5cec27c6107d4b86b3fa3750bd69a902299996fb

2024-06-19 12:43 UTC, apsantiso commented
/update-preview drive-server preview-443-f4e98fad68b03afa671ea125f6d969113305547e imageSuffix=-dev

2024-06-20 05:45 UTC, CandelR commented
/update-preview drive-server preview-443-f4e98fad68b03afa671ea125f6d969113305547e imageSuffix=-dev

2024-06-20 14:28 UTC, apsantiso commented
/update-preview drive-server preview-443-a110c66875e10a11f8800a59c9f11b2deab74e17 imageSuffix=-dev

2024-06-21 02:48 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-ce2ee04030b8466e7ecfdd78abb4eac28bd04f9e

2024-06-21 03:39 UTC, apsantiso commented
/update-preview drive-server preview-443-a110c66875e10a11f8800a59c9f11b2deab74e17 imageSuffix=-dev

2024-06-21 03:45 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-addaa2b9d7344f6dba540245a9c4c2c67ecaa690

2024-06-21 03:48 UTC, apsantiso commented
/update-preview drive-server preview-443-a110c66875e10a11f8800a59c9f11b2deab74e17 imageSuffix=-dev

2024-06-21 04:09 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-e6926a711c1ff2bec4c7ef3bc66d1a8d361692e9

2024-06-24 13:36 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-69717b8659e83c860322741482eed782962a10f8

2024-06-24 13:52 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-64b754824bc29ecc9cfdf5d3538ef7a67e100b3b

2024-06-25 05:52 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-4321b202539eaaf396f896c6ec98bc918208c5c6

2024-06-27 14:31 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-2334a256437d026f23d9963e9a3d44c2164267b7

2024-06-27 14:45 UTC, apsantiso commented
/update-preview drive-server-wip preview-287-4321b202539eaaf396f896c6ec98bc918208c5c6 imageSuffix=-dev

2024-06-28 02:19 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-e4853175716714113ca5f5e07e398ebf8f4db99e

2024-06-28 02:42 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-5f748643dbac25052eac2f4ec75acf31d418c77f

2024-06-28 03:06 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-4afdf562be38dd8e0637ce7f6372a69fc6727f1b

2024-07-01 14:26 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-7d2a2d0e4912bf7db6fb447b482c7534a364fc7d

2024-07-03 14:43 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-131d8ce15bd6e21ae44efc72506b8f250ef01726

2024-07-03 15:27 UTC, apsantiso commented
/update-preview drive-server preview-443-MjFhMTMwMTM2N2I3OWE1OTZlN2M4Mz imageSuffix=-dev

2024-07-03 15:33 UTC, apsantiso commented
/update-preview drive-server preview-443-MjFhMTMwMTM2N2I3OWE1OTZlN2M4Mz imageSuffix=-dev

2024-07-03 15:39 UTC, apsantiso commented
/update-preview drive-server preview-443-21a1301367b79a596e7c833f966297eeeb013334 imageSuffix=-dev

2024-07-04 06:16 UTC, CandelR commented
/update-preview drive-server preview-443-21a1301367b79a596e7c833f966297eeeb013334 imageSuffix=-dev

2024-07-04 07:48 UTC, apsantiso commented
/update-preview drive-server preview-443-21a1301367b79a596e7c833f966297eeeb013334 imageSuffix=-dev

2024-07-04 08:13 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-04 08:21 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-05 06:32 UTC, CandelR commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-08 06:03 UTC, CandelR commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-08 12:01 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-40ccdc99e3c0dd474cde7783ee15c6554831b3ca

2024-07-08 12:04 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-08 12:49 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-09 03:32 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-ae6775af62a9f0a12958f8653d57b7e6686c400b

2024-07-09 03:36 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-3e8b311c9174a9cac4eb589238c74f93970daca1

2024-07-09 03:42 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-09 04:20 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-e9962d40d31f4451e228bb7a3e14af148f827c9f

2024-07-09 04:24 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-09 04:59 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-fefd5e4729a675234b7e86b8845b0029fa2da5a1

2024-07-09 05:00 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-09 12:55 UTC, CandelR commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-10 02:45 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-869db915d42398580aa4b2415c85ebcdafe2019f

2024-07-10 02:59 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-10 13:43 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-f2b11b096112f3a38ccce5f0e067fd3ae4ccfb66

2024-07-10 13:44 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-10 14:21 UTC, apsantiso commented
/update-preview payments preview-73-9e42accbbcb80bca704929b494858127831db0f3 imageSuffix=-dev

2024-07-10 14:23 UTC, apsantiso commented
/update-preview payments preview-73-9e42accbbcb80bca704929b494858127831db0f3 imageSuffix=-dev

2024-07-10 14:24 UTC, apsantiso commented
/update-preview payment preview-73-9e42accbbcb80bca704929b494858127831db0f3 imageSuffix=-dev

2024-07-10 14:27 UTC, apsantiso commented
/update-preview payments preview-73-9e42accbbcb80bca704929b494858127831db0f3 imageSuffix=-dev

2024-07-10 14:30 UTC, apsantiso commented
/update-preview payments-dev preview-73-9e42accbbcb80bca704929b494858127831db0f3

2024-07-10 14:53 UTC, apsantiso commented
/update-preview payments-dp preview-73-9e42accbbcb80bca704929b494858127831db0f3 imageSuffix=-dev

2024-07-10 14:55 UTC, apsantiso commented
/update-preview payments preview-73-9e42accbbcb80bca704929b494858127831db0f3 imageSuffix=-dev

2024-07-10 14:58 UTC, apsantiso commented
/update-preview payments-server preview-73-9e42accbbcb80bca704929b494858127831db0f3 imageSuffix=-dev

2024-07-10 16:19 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-10 17:52 UTC, sg-gs commented
Reviewed the description of this PR to reduce noise @apsantiso

2024-07-11 09:16 UTC, sg-gs commented
Update the PR description again to mark new modules, models and repositories as merged. @apsantiso

2024-07-11 09:54 UTC, CandelR commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-11 10:33 UTC, inxtci commented
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Progressing**

2024-07-11 10:34 UTC, inxtci commented
> [!CAUTION]
> Pull request not updated after 5 minutes 💥
> We tried to update the image with drive-server-wip-dev:preview-287-7102a6571c661d338852994492206782dcdb57f8 
> If the arguments are correct, please check the logs. Or try again with another deployment, tag, or imageSuffix configuration.

2024-07-11 10:43 UTC, inxtci commented
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Progressing**

2024-07-11 10:43 UTC, inxtci commented
> [!CAUTION]
> Pull request not updated after 5 minutes 💥
> We tried to update the image with drive-server-wip-dev:preview-287-bf270ebe0e6ec03a12247338b58414e999cdc0e4 
> If the arguments are correct, please check the logs. Or try again with another deployment, tag, or imageSuffix configuration.

2024-07-11 12:04 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-11 12:06 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-bf270ebe0e6ec03a12247338b58414e999cdc0e4

2024-07-11 12:18 UTC, apsantiso commented
/check-preview  notify=true

2024-07-11 12:23 UTC, apsantiso commented
/check-preview

2024-07-11 12:26 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-11 12:28 UTC, apsantiso commented
/check-preview notify=true

2024-07-11 14:02 UTC, apsantiso commented
/update-preview payments-server preview-75-a77a8869c6845177649d5f06dea17686a040402d imageSuffix=-dev

2024-07-11 14:48 UTC, apsantiso commented
/update-preview payments-server preview-73-f97aa0c8877a9268e56395246774fa9349a57d04 imageSuffix=-dev

2024-07-11 14:51 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-11 15:26 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-11 15:40 UTC, inxtci commented
> [!NOTE]
> Pull request successfully updated 🚀
> Preview updated with drive-server-wip-dev:preview-287-e85a282c97625d30d0440eabe41d7e21aaa3d8e4

2024-07-11 15:45 UTC, inxtci commented
> [!CAUTION]
> Preview failed: Not deployed after 5 minutes check 💥
> **Last status received: Missing**

2024-07-11 16:12 UTC, apsantiso commented
/check-preview notify=true

2024-07-11 16:13 UTC, apsantiso commented
/update-preview drive-server preview-443-2d0b6c342eacc3b0604e161b53e5d2f80e8cfb5f imageSuffix=-dev

2024-07-12 13:56 UTC, sg-gs commented
Environment variables added. Deploying.

2024-07-12 13:56 UTC, merged