feat: setup workspace
internxt/drive-server-wip pull request #295
Opened 2024-04-11 02:51 UTC by apsantiso

2024-04-11 14:54 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.ts
> +    await this.workspaceRepository.addUserToWorkspace(workspaceUser);
Sorry this has to be drafted! However you are right, I need to check if workspace.owner === user before this. However, I think i will need to add the owner as workspaceUser in the initialize endpoint so the guard  in controllers can protect this endpoint successfully.

2024-04-12 04:54 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.ts
> +    await this.workspaceRepository.addUserToWorkspace(workspaceUser);
Solved this by adding an extra check to the guard and fetching the workspace with the respective filters to make sure it is the owner of it. Let me know if you were talking about another thing I missed.

2024-04-15 18:11 UTC, sg-gs requested changes

2024-04-15 18:11 UTC, sg-gs commented on src/modules/workspaces/guards/workspaces.guard.ts
> +      isWorkspaceNotSetup
This is a bit misleading. In reality, you are rejecting when the workspace is not set up and the user is not the owner.

2024-04-15 18:11 UTC, sg-gs commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      expect(workspaceRepository.addUserToWorkspace).toHaveBeenCalled();
Ensuring the function has been called with the owner's data would make this test stronger

2024-04-15 18:11 UTC, sg-gs commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      expect(teamRepository.addUserToTeam).toHaveBeenCalledWith(
Same here

2024-04-15 18:11 UTC, sg-gs commented on src/modules/workspaces/workspaces.usecase.ts
> +      throw new NotFoundException('There is no workspace to be setup');
Workspace not found would be better

2024-04-15 18:11 UTC, sg-gs commented on src/modules/workspaces/workspaces.usecase.ts
> +    await this.workspaceRepository.addUserToWorkspace(workspaceUser);
If this step fails, we may want to check which step is still failing, so in the case of a massive failure, we can just fix the error and users will only need to retry again. What do you think?

2024-04-17 13:05 UTC, sg-gs approved these changes

2024-04-18 01:50 UTC, merged