Workspaces Members
internxt/drive-server-wip pull request #299
Opened 2024-04-26 13:15 UTC by evillalba94

### Ticket
- https://inxt.atlassian.net/browse/PB-1842
### Updates
- Endpoint to get Workspace members.
- Update `createTeam` in the `workspaces.usecase` file to allow users (`Manager`) to be added to the team.
- Add new fixtures.
- Create tests for `usecase` and `controller`.

#### Endpoint
```
URL: /workspaces/:id/members
Method: GET
Authorization: Bearer {token}
```
![imagen](https://github.com/internxt/drive-server-wip/assets/83615039/823f7a32-a40a-4114-b9f0-3d71f5f750ca)

2024-05-07 09:37 UTC, apsantiso requested changes

2024-05-07 09:37 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      newWorkspaceTeamUser({
This might be something you missed to removed. You are not assigning it to any variable

2024-05-07 09:37 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      const mockWorkspaceUser = Promise.resolve([
Why are you calling promise.resolve?

2024-05-07 09:37 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      const getMembers = service.getWorkspaceMembers(workspace.id, owner);
You can use

```
const getMembers = await service.getWorkspaceMembers(workspace.id, owner);
await expect(getMembers).toStrictEqual(workspaceMembers);
      await expect(getMembers).toMatchObject([
        { isManager: true },
        { isManager: false },
      ]);
```

Yo do not need to use resolves every time, async await are the way to go if you want something cleaner.

2024-05-07 09:37 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      expect(workspaceUsers).toHaveBeenCalled();
Do not check if the method you are testing has been called.

2024-05-07 09:37 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      ).resolves.toStrictEqual([]);
This does not return []. Please run your tests before sending them.

```
    Expected: []
    Received: {"activatedUsers": [], "disabledUsers": []}
```

2024-05-07 09:37 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +
Use async await. Also, this does not return the value expected, isn't it? GetWorkspaceMembers always return {activatedUser: [], deactivatedUser: []}

```
 FAIL  src/modules/workspaces/workspaces.usecase.spec.ts (6.179 s)
  ● WorkspacesUsecases › getWorkspaceMembers › When there are no members then return an empty array

    expect(received).resolves.toStrictEqual(expected) // deep equality

    Expected: []
    Received: {"activatedUsers": [], "disabledUsers": []}

      981 |       await expect(
      982 |         service.getWorkspaceMembers(workspace.id, owner),
    > 983 |       ).resolves.toStrictEqual([]);
          |                  ^
      984 |
      985 |       expect(workspaceUsers).toHaveBeenCalled();
      986 |     });

      at Object.toStrictEqual (node_modules/expect/build/index.js:174:22)
      at Object.<anonymous> (src/modules/workspaces/workspaces.usecase.spec.ts:983:18)
```

2024-05-07 09:37 UTC, apsantiso commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +        .mockResolvedValue(Promise.resolve(workspace));
Why are you using promise.resolve? Please follow the previous tests here, you have a lot of previous examples.

2024-05-07 09:39 UTC, apsantiso commented
Please @jvedrson  follow the guidelines and previous examples in your tests. Most of the tests you can create for this case can be covered following previous unit tests. 

Also, please run your tests before send this, they are failing. We need tests to be running properly to trust this is working as expected.

2024-05-07 09:47 UTC, sg-gs commented on src/modules/workspaces/domains/workspace-user.domain.ts
> +    return (BigInt(this.driveUsage) + BigInt(this.backupsUsage)).toString();
Yes, why is the conversion needed? We should keep the raw format as long as a conversion is not needed for a backend-related operation.

2024-05-07 09:47 UTC, sg-gs commented on src/modules/workspaces/domains/workspace-user.domain.ts
> +  getFreeSpace(): string {
Same here

2024-05-07 09:48 UTC, apsantiso requested changes

2024-05-07 09:48 UTC, apsantiso commented on src/modules/workspaces/workspaces.controller.spec.ts
> +      await expect(resFailed).rejects.toThrow();
This is probably going to fail if the promise resolves before. use async await

2024-05-07 09:48 UTC, apsantiso commented on src/modules/workspaces/workspaces.controller.spec.ts
> +      expect(workspaceController).toHaveBeenCalledTimes(1);
Do not test if the function you are testing right now is being called.

2024-05-07 09:48 UTC, apsantiso commented on src/modules/workspaces/workspaces.controller.spec.ts
> +        });
why are you mocking the implementation? The meaning of tests is to test the real implementation, not mocking it.  

You should mock external usecases or repositories if the controller depends on it. If the controller is too simple and you just need to add tests for coverage, then create a simple test that just checks if the controller returns what the usecase returns and that's it.

2024-05-07 09:48 UTC, sg-gs commented on src/modules/workspaces/workspaces.controller.spec.ts
> +      expect(workspaceController).toHaveBeenCalled();
Agree, as long as you test the behavior of the function and its subfunctions (functions called from the function you are testing) it is fine and enough.

2024-05-07 09:52 UTC, sg-gs requested changes

2024-05-07 09:52 UTC, sg-gs commented on src/modules/workspaces/workspaces.controller.spec.ts
> +      expect(workspaceController).toHaveBeenCalledTimes(1);
Same here, do not check that the function you are testing is called, of course is called, you have done it explicitly when running the test.

2024-05-07 09:52 UTC, sg-gs commented on src/modules/workspaces/workspaces.controller.spec.ts
> +      expect(workspaceUsecase).toHaveBeenCalledWith(workspace.id, owner);
Same here

2024-05-07 09:52 UTC, sg-gs commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      expect(getWorkspace).toHaveBeenCalled();
Same here

2024-05-07 09:52 UTC, sg-gs commented on src/modules/workspaces/workspaces.usecase.spec.ts
> +      expect(workspaceUsers).toHaveBeenCalled();
Same here

2024-05-07 20:47 UTC, jvedrson commented on src/modules/workspaces/attributes/workspace-users.attributes.ts
> +  member?: any;
This is taken from other examples in the code. This interface in the `member` field could be diff (User, UserModel, etc), so the validation of what Interface we are going to use are inside the files where this interface `WorkspaceUserAttributes` is required.

![image](https://github.com/internxt/drive-server-wip/assets/38819324/86e13835-aab1-43c5-aab3-ea9d4b3f744e)

2024-05-09 10:31 UTC, apsantiso approved these changes

2024-05-09 10:32 UTC, merged