[PB-2284]: Feat/register notification token endpoint
internxt/drive-server-wip pull request #341
Opened 2024-06-25 22:49 UTC by jzunigax2

Added `user_notification_tokens` table and an endpoint to register these device tokens. Currently, this is aimed at implementing Apple's push notification service for the macOS client to signal real-time changes. Still, the new table contains a type property in case this could be used for a different purpose in the future.

2024-06-27 12:48 UTC, sg-gs requested changes
This PR is not handling three things related to the security and abuse prevention of this API: 
- Throttling requests on that endpoint
- Removal process of those tokens: do they expire or something?
- Setting a max number of tokens per user: we do not want to allow 20 devices to be connected. Up to 10 is fine for now.

@PixoDev @jzunigax2

2024-06-27 13:34 UTC, jzunigax2 commented
> This PR is not handling three things related to the security and abuse prevention of this API:
> 
>     * Throttling requests on that endpoint
> 
>     * Removal process of those tokens: do they expire or something?
> 
>     * Setting a max number of tokens per user: we do not want to allow 20 devices to be connected. Up to 10 is fine for now.
> 
> 
> @PixoDev @jzunigax2

It seems Apple's tokens don't have an expiration date. However, when sending a notification the API could respond with 410, indicating that the token is no longer active due to a variety of reasons. I'll make sure to handle this case when integrating the APN service.

@sg-gs

2024-07-01 10:39 UTC, sg-gs approved these changes

2024-07-01 10:42 UTC, sg-gs commented
Migration run @jzunigax2 

```
Loaded configuration file "src/config/sequelize.js".
Using environment "production".
== 20240624200747-create-user-tokens-table: migrating =======
== 20240624200747-create-user-tokens-table: migrated (0.352s)

✨  Done in 2.52s
```

2024-07-01 10:42 UTC, merged