[PB-2424] Chore: use query to get information about Shared Items
internxt/drive-server-wip pull request #399
Opened 2024-09-27 13:40 UTC by evillalba94

### Update
- Fix: using `query` to get the information about `isSharedItem`. 

### Related to
- sdk : https://github.com/internxt/sdk/pull/246
- web : https://github.com/internxt/drive-web/pull/1290

2024-10-02 13:41 UTC, sg-gs commented
Title "Chore: use query to get information", information about what @evillalba94 ? Please be more specific about that in the PR title

2024-10-02 14:18 UTC, evillalba94 commented
> Title "Chore: use query to get information", information about what @evillalba94 ? Please be more specific about that in the PR title

@sg-gs Ok, I made the change.

2024-10-21 11:52 UTC, apsantiso requested changes

2024-10-21 11:52 UTC, apsantiso commented on src/modules/workspaces/guards/workspaces-resources-in-items-in-behalf.guard.ts
> +    const bypassActionCheck = request.query?.isSharedItem || false;
This bypasses guard's security @jvedrson, please read this https://github.com/internxt/drive-server-wip/pull/407#issuecomment-2414125396 

Is sharedItem part in the request is used to let the workspaceGuard know that is it a sharedItem and bypass but we can not let the frontend decide that, that's something the backend should determine.

2025-01-23 14:36 UTC, apsantiso commented
Duplicated of https://github.com/internxt/drive-server-wip/pull/445, I am closing this to leave the most recent one

2025-01-23 14:36 UTC, closed without merging