[_]: feat/add unique constraint on member_id and workspace_id in workspace_users and workspace_teams_users
internxt/drive-server-wip pull request #421
Opened 2024-11-04 15:32 UTC by jzunigax2

Add UNIQUE constraints with `workspace_id` and `member_id` in `workspace_users` and `workspace_teams_users` to prevent duplicated members

2024-11-05 12:41 UTC, sg-gs commented
Please add a description of why you are doing this @jzunigax2. In this case, something like "Add UNIQUE constraint with workspace_id and member_id to prevent duplicated members in a given workspace" would be a good concise description. Otherwise the context of the why of this change, is lost.

2024-11-05 12:42 UTC, sg-gs requested changes

2024-11-05 12:42 UTC, sg-gs commented on migrations/20241104161535-add-unique-constraint-memberid-teamid.js
> +      fields: ['member_id', 'team_id'],
This was not mentioned neither in the PRs description nor in the title

2025-05-15 23:04 UTC, jzunigax2 commented on migrations/20250512161535-add-unique-constraint-memberid-teamid.js
> +    await queryInterface.addConstraint(table_name, {
it was indeed blocking, I changed it to instead create an index using concurrently

2025-05-15 23:09 UTC, jzunigax2 commented on src/modules/workspaces/repositories/team.repository.ts
> +        error.name === 'SequelizeUniqueConstraintError' &&
The use case does check this condition before attempting insertion, but due to the race condition that can sometimes affect this use case whenever this insertion fails it would just throw a 500 error. while this ensures to catch the error and rethrow a 400 which is what frontend handles

2025-05-16 08:27 UTC, sg-gs commented on src/modules/workspaces/repositories/team.repository.ts
> +        error.name === 'SequelizeUniqueConstraintError' &&
If we are doing the proper async management, no race condition should happen, especially on small tables like this one, that is even under a thousand records which is far far less than for instance the files table, which thousands of millions of records. This does not seem logical or fundamented, describe how that happens and which steps need to be done to trigger that race condition.

2025-05-16 21:11 UTC, jzunigax2 commented on src/modules/workspaces/repositories/team.repository.ts
> +        error.name === 'SequelizeUniqueConstraintError' &&
We have seen this happen twice now. First, back in November, while working on workspace limit adjustments for members, we applied a script that would grant the workspace owner all unassigned space. After doing so, two owners were assigned negative space limits due to the workspace containing more members than its plan allowed. After further investigation, we found back then that these extra members were duplicates, with a createdAt at almost the exact second. If you take a look at the [source code](https://github.com/internxt/drive-server-wip/blob/c97948ac4692b5479f8d8678d3ad6820a35f0e50/src/modules/workspaces/workspaces.usecase.ts#L1695-L1742) you can see that many db calls are made between the check userAlreadyInWorkspace and the actual insertion. This can be replicated by attempting to quickly click on accept invite when prompted in drive-web

Now, more recently, we had a bug report where a workspace owner reported their workspace appeared duplicated on web's workspace selector. In this case, the use case that sets up a workspace was called in repeated succession. If you take a look at the [source code](https://github.com/internxt/drive-server-wip/blob/c97948ac4692b5479f8d8678d3ad6820a35f0e50/src/modules/workspaces/workspaces.usecase.ts#L242-L265) you'll see that a couple of db plus one network call are made between the userAlreadyInWorkspace check and the actual user insertion, leaving enough room for a race condition. 

We could simply rerun the checks right before insertion, but still, wouldn't there be some chance of a race condition (albeit very slim, probably negligible)?

2025-07-01 00:52 UTC, jzunigax2 commented
Closing this as proposed solution was not accepted, we may need to revist this in the future with a different scope. Perhaps only with the migrations that introduce a unique

2025-07-01 00:52 UTC, closed without merging